<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Minecraft Server Info</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body {
      font-family: 'Segoe UI', sans-serif;
      margin: 0;
      background-color: #1e1e1e;
      color: #e0e0e0;
    }

    header {
      background-color: #2c2c2c;
      padding: 20px;
      text-align: center;
    }

    nav a {
      color: #a6e22e;
      margin: 0 10px;
      text-decoration: none;
      font-weight: bold;
    }

    section {
      padding: 40px 20px;
      max-width: 700px;
      margin: auto;
    }

    h2 {
      color: #a6e22e;
    }

    input, textarea, button {
      width: 100%;
      padding: 10px;
      margin-top: 10px;
      border: none;
      border-radius: 5px;
      font-size: 1em;
    }

    button {
      background-color: #a6e22e;
      color: #000;
      font-weight: bold;
      cursor: pointer;
    }

    .server-list {
      background: #2a2a2a;
      padding: 15px;
      margin-top: 20px;
      border-radius: 6px;
    }

    .server-item {
      background: #333;
      padding: 10px;
      margin-bottom: 10px;
      border-left: 5px solid #a6e22e;
      position: relative;
    }

    .action-buttons {
      margin-top: 10px;
    }

    .edit-btn, .delete-btn {
      padding: 5px 10px;
      margin-right: 10px;
      font-size: 0.9em;
      border: none;
      border-radius: 3px;
      cursor: pointer;
    }

    .edit-btn {
      background-color: #66d9ef;
      color: #000;
    }

    .delete-btn {
      background-color: #f92672;
      color: #fff;
    }

    footer {
      text-align: center;
      padding: 20px;
      background: #2c2c2c;
      font-size: 0.9em;
    }
  </style>
</head>
<body>

  <header>
    <h1>My Minecraft Server Site</h1>
    <nav>
      <a href="#home">Home</a>
      <a href="#about">About</a>
      <a href="#submit">Submit Server</a>
      <a href="#contact">Contact</a>
    </nav>
  </header>

  <section id="home">
    <h2>Welcome</h2>
    <p>Join our Minecraft community! Submit your server info below and we'll show it to the world.</p>
  </section>

  <section id="about">
    <h2>About</h2>
    <p>This site is made by Minecraft players to help you promote your own survival, creative, or minigame server.</p>
  </section>

  <section id="submit">
    <h2>Submit Your Server</h2>
    <form id="serverForm">
      <input type="text" id="serverName" placeholder="Server Name" required />
      <input type="text" id="serverIP" placeholder="Server IP Address" required />
      <input type="text" id="serverVersion" placeholder="Minecraft Version" required />
      <textarea id="serverDesc" placeholder="Short Description (optional)"></textarea>
      <input type="hidden" id="editIndex" value="" />
      <button type="submit">Save Server</button>
    </form>

    <div class="server-list" id="serverList">
      <h3>Submitted Servers</h3>
      <!-- Server items appear here -->
    </div>
  </section>

  <section id="contact">
    <h2>Contact</h2>
    <p>Reach out on Discord or email: <strong>vikrambryadav@gmail.com</strong></p>
  </section>

  <footer>
    <p>&copy; 2025 My Minecraft Server Site. All rights reserved.</p>
  </footer>

  <script>
    const form = document.getElementById("serverForm");
    const serverListEl = document.getElementById("serverList");
    let servers = JSON.parse(localStorage.getItem("servers")) || [];

    function saveServers() {
      localStorage.setItem("servers", JSON.stringify(servers));
    }

    function renderServers() {
      serverListEl.innerHTML = "<h3>Submitted Servers</h3>";
      servers.forEach((server, index) => {
        const serverEl = document.createElement("div");
        serverEl.classList.add("server-item");
        serverEl.innerHTML = `
          <strong>${server.name}</strong><br>
          IP: ${server.ip}<br>
          Version: ${server.version}<br>
          ${server.desc ? `<em>${server.desc}</em><br>` : ""}
          <div class="action-buttons">
            <button class="edit-btn" onclick="editServer(${index})">Edit</button>
            <button class="delete-btn" onclick="deleteServer(${index})">Delete</button>
          </div>
        `;
        serverListEl.appendChild(serverEl);
      });
    }

    function editServer(index) {
      const server = servers[index];
      document.getElementById("serverName").value = server.name;
      document.getElementById("serverIP").value = server.ip;
      document.getElementById("serverVersion").value = server.version;
      document.getElementById("serverDesc").value = server.desc;
      document.getElementById("editIndex").value = index;
    }

    function deleteServer(index) {
      if (confirm("Are you sure you want to delete this server?")) {
        servers.splice(index, 1);
        saveServers();
        renderServers();
      }
    }

    form.addEventListener("submit", function (e) {
      e.preventDefault();
      const name = document.getElementById("serverName").value.trim();
      const ip = document.getElementById("serverIP").value.trim();
      const version = document.getElementById("serverVersion").value.trim();
      const desc = document.getElementById("serverDesc").value.trim();
      const editIndex = document.getElementById("editIndex").value;

      if (!name || !ip || !version) {
        alert("Please fill in all required fields.");
        return;
      }

      const serverData = { name, ip, version, desc };

      if (editIndex === "") {
        // Add new
        servers.push(serverData);
      } else {
        // Edit existing
        servers[editIndex] = serverData;
        document.getElementById("editIndex").value = "";
      }

      saveServers();
      renderServers();
      form.reset();
    });

    // Load saved servers
    renderServers();
  </script>
</body>
</html>

